const root=document.querySelector('#view-root'),runButton=document.querySelector('#run-button'),resetButton=document.querySelector('#reset-button'),liveStatus=document.querySelector('#live-status'),title=document.querySelector('#page-title');
const views=new Set(['home','runs','context','evidence','memory','design']);let dashboard=null;
async function load(){root.setAttribute('aria-busy','true');const response=await fetch('/api/dashboard');if(!response.ok)throw new Error('Could not load local dashboard');dashboard=await response.json();render();root.setAttribute('aria-busy','false')}
function currentView(){const value=new URL(location.href).searchParams.get('view')??'home';return views.has(value)?value:'home'}
function render(){const view=currentView();title.textContent=view[0].toUpperCase()+view.slice(1);for(const link of document.querySelectorAll('[data-view]'))link.toggleAttribute('aria-current',link.dataset.view===view);root.innerHTML=({home:renderHome,runs:renderRuns,context:renderContext,evidence:renderEvidence,memory:renderMemory,design:renderDesign})[view]();root.querySelectorAll('[data-action=run]').forEach(button=>button.addEventListener('click',runDemo));root.querySelectorAll('[data-run-id]').forEach(link=>link.addEventListener('click',showRun))}
function renderHome(){const metrics=dashboard.metrics,latest=dashboard.latestRun;return `<section class="metrics" aria-label="Workspace metrics">${metric(metrics.runs,'Runs')}${metric(metrics.completed,'Completed')}${metric(metrics.events,'Events')}${metric(metrics.pendingApprovals,'Pending approvals')}</section><section class="grid-two"><div class="panel"><div class="panel-header"><h2>Recent runs</h2><span class="muted">Local event ledger</span></div>${runList(dashboard.runs)}</div><div class="panel"><div class="panel-header"><h2>Context budget</h2><span class="muted">Latest compile</span></div>${contextSummary(dashboard.latestManifest)}</div></section><section class="panel"><div class="panel-header"><h2>Latest recommendations</h2><span class="muted">Synthetic evidence only</span></div>${angles(latest?.output?.output)}</section>`}
function renderRuns(){return `<section class="panel"><div class="panel-header"><h2>Run history</h2><span class="muted">Deep links and event traces</span></div>${runList(dashboard.runs)}</section>`}
function renderContext(){const manifest=dashboard.latestManifest;if(!manifest)return empty('No context manifest yet','Run the local workflow to inspect selected and excluded records.');return `<section class="grid-two"><div class="panel"><div class="panel-header"><h2>Selected context</h2><span class="muted">${manifest.selected.length} records</span></div>${manifestList(manifest.selected)}</div><div class="panel"><div class="panel-header"><h2>Excluded context</h2><span class="muted">${manifest.excluded.length} records</span></div>${manifestList(manifest.excluded)}</div></section>`}
function renderEvidence(){const manifest=dashboard.latestManifest,items=(manifest?.selected??[]).filter(item=>item.kind==='observation');if(!items.length)return empty('No selected evidence yet','Run the local workflow to inspect source-backed observations.');return `<section class="panel"><div class="panel-header"><h2>Selected evidence</h2><span class="muted">Observation is separate from inference</span></div><div class="evidence-list">${items.map(item=>`<article class="evidence-card"><header><code>${esc(item.id)}</code><span class="trust-label">untrusted source data</span></header><p>${esc(item.text)}</p><div class="meta-row"><span>Source: ${esc(item.source)}</span><span>${item.tokens} tokens</span></div><div class="reason-list">${item.reasonCodes.map(reason=>`<span class="reason">${esc(reason)}</span>`).join('')}</div></article>`).join('')}</div></section>`}
function renderMemory(){return `<section class="panel"><div class="panel-header"><h2>Memory lifecycle</h2><span class="muted">Specified; not persisted in bootstrap</span></div><p>Permanent records move through <code>observed → proposed → verified → active → superseded / retracted / expired</code>.</p><pre>${esc(JSON.stringify({id:'mem_example',kind:'preference',status:'active',supersedes:'mem_previous',confidence:.94,source:'user-confirmed'},null,2))}</pre></section>`}
function renderDesign(){const swatches=[['Ink','#0A0B0D'],['Signal','#56E0C4'],['Proof','#8BA7FF'],['Caution','#F2B84B'],['Danger','#F06A6A'],['Success','#72D39C']];return `<section class="panel"><div class="panel-header"><h2>Design contract</h2><span class="muted">Local system tokens</span></div><p>Outcome-first disclosure, stable URLs, visible focus, and explicit trust boundaries. <code>DESIGN.md</code> is canonical.</p><div class="token-grid">${swatches.map(([name,value])=>`<div class="swatch" style="background:${value}"><strong>${name}<br><code>${value}</code></strong></div>`).join('')}</div></section>`}
function metric(value,label){return `<div class="metric"><strong>${value}</strong><span>${label}</span></div>`}
function runList(items){if(!items?.length)return empty('No runs yet','Execute the synthetic local workflow to populate the event ledger.',true);return `<div class="run-list">${items.map(run=>`<article class="run-card"><header><a href="/?view=runs&run=${encodeURIComponent(run.id)}" data-run-id="${esc(run.id)}">${esc(run.workflowId)}</a><span class="status ${esc(run.status)}">${esc(run.status)}</span></header><p>${esc(run.objective??'')}</p><div class="meta-row"><code>${esc(run.id)}</code><span>${date(run.createdAt)}</span></div></article>`).join('')}</div>`}
function contextSummary(manifest){if(!manifest)return '<p class="muted">No context has been compiled.</p>';const percent=Math.min(100,Math.round(manifest.budget.used/manifest.budget.available*100));return `<strong>${manifest.budget.used} / ${manifest.budget.available} estimated tokens</strong><div class="progress" aria-label="${percent}% of context budget used"><span style="width:${percent}%"></span></div><p class="muted">${manifest.selected.length} selected · ${manifest.excluded.length} excluded · ${manifest.conflicts.length} conflicts</p>`}
function manifestList(items){if(!items?.length)return '<p class="muted">None.</p>';return `<div class="manifest-list">${items.map(item=>`<article class="manifest-item"><header><code>${esc(item.id)}</code><span>${item.tokens} tokens</span></header>${item.text?`<p>${esc(item.text)}</p>`:''}<div class="reason-list">${item.reasonCodes.map(reason=>`<span class="reason">${esc(reason)}</span>`).join('')}</div></article>`).join('')}</div>`}
function angles(items){if(!Array.isArray(items)||!items.length)return '<p class="muted">Run the demo to generate evidence-backed candidates.</p>';return `<div class="angle-list">${items.map(item=>`<article class="angle"><h3>${esc(item.angle)}</h3><p>${esc(item.hook)}</p><div class="meta-row"><span>Evidence: ${item.evidenceIds.map(esc).join(', ')||'none'}</span><span>Confidence: ${Math.round(item.confidence*100)}%</span></div></article>`).join('')}</div>`}
function empty(heading,copy,button=false){return `<div class="empty-state"><h2>${heading}</h2><p>${copy}</p>${button?'<button class="button primary" data-action="run" type="button">Run local demo</button>':''}</div>`}
async function runDemo(){runButton.disabled=true;runButton.textContent='Running…';liveStatus.textContent='Local workflow started.';try{const response=await fetch('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workflowId:'workflow:content-intelligence'})});if(!response.ok)throw new Error('Workflow failed to start');await load();liveStatus.textContent='Local workflow completed.'}catch(error){liveStatus.textContent=error.message}finally{runButton.disabled=false;runButton.textContent='Run local demo'}}
async function resetDemo(){resetButton.disabled=true;try{await fetch('/api/reset',{method:'POST'});await load();liveStatus.textContent='Local demo data reset.'}finally{resetButton.disabled=false}}
async function showRun(event){event.preventDefault();const id=event.currentTarget.dataset.runId;history.pushState({},'',`/?view=runs&run=${encodeURIComponent(id)}`);const response=await fetch(`/api/runs/${encodeURIComponent(id)}`);const data=await response.json();title.textContent='Run detail';root.innerHTML=`<section class="grid-two"><div class="panel"><div class="panel-header"><h2>${esc(data.run.workflowId)}</h2><span class="status ${esc(data.run.status)}">${esc(data.run.status)}</span></div><p>${esc(data.run.objective)}</p>${angles(data.run.output?.output)}${data.run.verification?.valid?'<p class="verified-note">✓ Evidence references verified against selected context.</p>':''}</div><div class="panel"><div class="panel-header"><h2>Event timeline</h2><span class="muted">${data.events.length} events</span></div><div class="timeline">${data.events.map(item=>`<article class="event"><span class="event-marker"></span><div><h3>${esc(item.type)}</h3><p>${date(item.occurredAt)} · ${esc(item.actorId)}</p></div></article>`).join('')}</div></div></section>`}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function date(value){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'}
runButton.addEventListener('click',runDemo);resetButton.addEventListener('click',resetDemo);window.addEventListener('popstate',render);load().catch(error=>{root.innerHTML=empty('Could not load local state',esc(error.message))});
